FROM postgres:14.1-alpine

COPY ./.env /app/.env

ENV POSTGRES_USER=$API_USER
ENV POSTGRES_PASSWORD=$API_PASSWORD
ENV POSTGRES_DB=$API_DATABASE
ENV POSTGRES_HOST=$POSTGRES_HOST

RUN mkdir -p /var/lib/postgresql/data
COPY ./db/words.sql /docker-entrypoint-initdb.d/init.sql

EXPOSE $PG_DOCKER_PORT

HEALTHCHECK CMD-SHELL sh -c "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" \
  INTERVAL 10s \
  TIMEOUT 5s \
  RETRIES 5

VOLUME 295wordsdata:/var/lib/postgresql/data


