FROM node:16-alpine AS builder

WORKDIR /295fullstack

COPY ./frontend/package.json  ./

RUN apk add yarn
RUN apk add bash
RUN apk add curl

RUN yarn install --frozen-lockfile
RUN yarn add dotenv

COPY ./frontend/ .
RUN echo "API_URI=http://295fsbe:5000/api/topics" > .env
RUN echo " " > .env

RUN sed -i '/"scripts": {/a\    "start:with-env": "node -r dotenv/config server.js",' package.json

EXPOSE 3000

CMD ["yarn", "run", "start:with-env"]
