FROM node:16-alpine AS builder

WORKDIR /295fullstack

COPY ./frontend/package.json  ./

RUN apk add yarn

RUN yarn install --frozen-lockfile

COPY ./frontend/ .
RUN echo "API_URI=http://295fsbe:5000/api/topics" > .env
ENV API_URI http://295fsbe:5000/api/topics

CMD ["node", "server.js"]
