FROM node:18-alpine AS builder

WORKDIR /295shoponline

COPY ./devopsbc_p1_be_scart/*.json  ./

RUN apk add yarn
RUN apk add bash
RUN apk add curl

RUN yarn install --frozen-lockfile

COPY ./devopsbc_p1_be_scart/. .

EXPOSE 3002

CMD ["node", "server.js"]
